- name: Build the load balancer image 
  docker_image:
    build:
      path: ./roles/lb/templates/
    name: my_load_balancer
    source: "build"

- name: Build the lb_container container from the my_nginx image
  docker_container:
    name: lb_contailbner
    image: my_load_balancer
    networks:
      - name: homework
    ports:
    - "8000:8000"