name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ['main']
    # Pattern matched against refs/tags
    tags:        
      - '**'           # Push events to every tag not containing /
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
    
      - name: Build and Push Mongodb Image
        uses: docker/build-push-action@v2
        with:
          context: ./roles/db/templates/
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my_db
          push: true    
        

      
 




