on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  coverage-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start MongoDB
        run: |
          sudo service mongod start

      - name: Wait for MongoDB to start
        run: |
          sleep 10s

      - name: Run tests
        run: |
          python app.py
          python test.py

      - name: Generate coverage report
        run: |
          python -m coverage run test.py
          python -m coverage report -m

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./htmlcov
