name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    type: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  Coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r flask/requirements.txt
      - name: Run tests and generate coverage report
        run: |
          python flask/server.py test
      - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 90
          skip-step: install
