name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '*'

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['5.0']


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install libary
        run: |
          python -m pip install --upgrade pip
          pip install -r roles/api/files/requirements.txt

      - name: test
        run:
          python roles/api/files/manage.py test
 